version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: translation-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: translation_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - translation-network

  app:
    build: .
    container_name: translation-app
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/translation_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    networks:
      - translation-network

volumes:
  mysql_data:

networks:
  translation-network:
    driver: bridge