server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: translation-service
  
  datasource:
    url: jdbc:mysql://localhost:3306/translation_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        jdbc:
          batch_size: 1000
        order_inserts: true
        order_updates: true
        
  cache:
    type: simple
    
  security:
    user:
      name: admin
      password: admin123

app:
  jwt:
    secret: myVerySecretKeyForJWTTokenGenerationAndValidation
    expiration: 86400000 # 24 hours

logging:
  level:
    com.digitaltolk.translation: INFO
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
